### ISSUE TITLE
Migrate rustc_inferface queries

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/compiler-team#175]
# Meeting proposal info

- **Title:** Migrate rustc_interface queries
- **Type:** technical
- **Proposed by:** pnkfelix, Zoxc
- **Link:** [internals post](https://internals.rust-lang.org/t/migrating-rustc-interface-queries-to-proper-librustc-queries/10433)
   * (aka PRs rust-lang/rust#59064, rust-lang/rust#59205, rust-lang/rust#59282, rust-lang/rust#59338, rust-lang/rust#59404, rust-lang/rust#59904)
- **Scheduled dates for discussion:**
  - Not yet scheduled, we'll add content here when it gets scheduled

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/about/steering-meeting.md
[proc]: https://github.com/rust-lang/compiler-team/blob/master/procedures/steering-meeting.md
[this template]: https://github.com/rust-lang/compiler-team/blob/master/proposals/_template.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by nikomatsakis** [comment]
We [discussed this](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/design.20meeting.202019-09-27/near/176750701) in today's [planning meeting](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/design.20meeting.202019-09-27). 

We decided to **schedule this meeting for Oct 11** -- though since @Zoxc wasn't at the meeting, that was only tentative. 

We also discussed how to help focus and guide the meeting agenda. The plan is for @pnkfelix to touch base with @Zoxc and to try and pick one specific PR or proposal to discuss. @pnkfelix can try to understand what is being proposed before-hand so that we can discuss it more as a group. Ideally, we would have pre-prepared a document (e.g., on hackmd) that documents the design and which can be later converted into a rustc-guide chapter. We should also aim, in the meeting, to talk about the downsides and whether this PR is a reasonable *end-state* or what kind of follow-up work we would want to do before we are comfortable leaving things as they are.

**Comment by nikomatsakis** [comment]
We wound up discussing something slightly different: PR #62038. We also decided to do a follow-up discussion to cover #60035, but I'll file an issue on that separately.

**Comment by nikomatsakis** [comment]
We've scheduled this for discussion on [December 6](https://calendar.google.com/event?action=TEMPLATE&tmeid=MTByaTZsZG1pZGI1Y2RqdGZ1cHV2djNncTEgNnU1cnJ0Y2U2bHJ0djA3cGZpM2RhbWdqdXNAZw&tmsrc=6u5rrtce6lrtv07pfi3damgjus%40group.calendar.google.com).
