### ISSUE TITLE
Move `src/test/run-fail` tests to UI

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/compiler-team#274]
# TL;DR
Move `src/test/run-fail` tests to UI to unify the test structure.

# Links and Details
- submitted PR: rust-lang/rust#71185
- original issue: rust-lang/rust#65440
-  unresolved issue: rust-lang/rust#65865
- previous attmpt: rust-lang/rust#65506

## Questions
- Does this remove all uses of run-fail?
- How will rust-lang/rust#65865 get resolved?
- Any other lingering bits of work?

# Mentors or Reviewers
@nikomatsakis

**Comment by petrochenkov** [comment]
I support the change, multiple other test suites were already successfully migrated to UI, including `run-pass`.

If some tests cannot be migrated right now due to heavily platform-dependent output or similar reasons, they can stay in `run-fail` for now and be dealt with later.

It's more convenient to fix https://github.com/rust-lang/rust/issues/65865 *after* the `run-fail` -> `ui` change, but soon enough to avoid new uses of `error-pattern` for runtime output.

**Comment by Mark-Simulacrum** [comment]
(I suspect @petrochenkov may have forgotten to, but regardless I'm willing to do it: @rustbot seconded).

**Comment by Mark-Simulacrum** [comment]
Gah, bad bot, @rustbot seconded.

**Comment by petrochenkov** [comment]
I didn't even know the automation was already implemented.
Is it documented anywhere?

**Comment by nikomatsakis** [comment]
**Huzzah!** This proposal has been accepted.
