### ISSUE TITLE
Update the existing musl targets to be dynamically linked.

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/compiler-team#422]
# Update the existing musl targets to be dynamically linked.

We should change the `-musl` targets to be consistently dynamically linked to their `libc`, rather than statically linking the `musl` libc into them at compile-time. If a MUSL end-user wants the musl-libc to be statically-linked into their program, they will need to specify it explicitly (e.g. via `-Ctarget-feature=+crt-static`)

Proposed Mitigation Strategy: In order to give the current users a chance to prepare for this change, we will first land a lint on all hosts that target musl. This lint will warn that the defaults here are going to change (namely, that the implicit `+crt-static` is switching to `-crt-static`). The lint will be silenced by explicitly providing either `+crt-static` or `-crt-static`.

Why we should do this: This would make Rust's `-musl` targets more consistent on two axes: It would make them more consistent with Rust's non-musl targets (which likewise dynamically link to the target's libc), and it would make them consistent with what musl toolchains expect, especially the toolchains for musl-based Linux distributions. (Today, musl-based Linux distribtuons are locally patching Rust to get the behavior they expect.)

Why we might not do this: It is a breaking change. The current defaults were put in place to support a specific use case of producing shippable binaries, and changing the default will break users who are not explicitly (and, with the current defaults, redundantly) requesting `+crt-static`. However, the mitigation strategy is intended to address the needs of those users.

Background: Rust currently has Tier 2 targets for a number of platforms using musl for libc (various flavors of ARM, MIPS and x86) as well as some Tier 3 targets (Hexagon, PowerPC, RISC-V, S390x and ARMv7 Thumb). Currently (most of) these targets statically link to musl libc during compilation.
ts could also be added.

# Mentors or Reviewers

This MCP is an outcome from the compiler-team design meeting [compiler-team#416](https://github.com/rust-lang/compiler-team/issues/416) ([zulip archive](https://zulip-archive.rust-lang.org/238009tcompilermeetings/10080designmeeting20210326musllinkingcompilerteam416.html))

I expect the stake-holders who participated in that meeting to be involved, though they may not be the actual mentors. 

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by petrochenkov** [comment]
The correct combination of flags to preserve the old behavior is
```sh
-C target-feature=+crt-static -C link-self-contained=yes
```
because the old musl targets not only link libc statically by default, they also link libc and crt objects shipped with rustc by default, which is also undesirable.

Besides that, cargo need to be convinced to pass these flags only when compiling for the target, and not for the host (proc macros, build scripts).

**Comment by Timmmm** [comment]
-C target-feature=+crt-static -C link-self-contained=yes

That's quite a pain when most users using the `musl` targets are primarily doing it so that they get a statically linked binary and don't have to deal with glibc compatibility issues.

This should only be done once there is a more user friendly way to get the current behaviour.

**Comment by Diggsey** [comment]
cc @emk who maintains a widely used docker image for building static musl binaries.

**Comment by ssokolow** [comment]
For context, I use `musl` targets for using pure Rust to write "shell scripts" that need to meet high standards of reliability, so I consider a Docker-based solution a deal-breaker.

Docker simply adds far too much delay and complexity to the compilation cycle for that kind of use-case... not to mention that I've spent the last few years promoting "For pure-Rust projects, Go-like static builds are as simple as `rustup target add` and `cargo build --target`" as a virtue of the language.

**Comment by Diggsey** [comment]
> Docker simply adds far too much delay and complexity to the compilation cycle

Not sure if that was directed at my comment, but I'm not suggesting that everyone should use the docker image, just that the author and users of that docker image would be impacted by this potential change and should know about it.

**Comment by ssokolow** [comment]
I was unsure what your intent was, so I left whether I was replying to you ambiguous.

**Comment by wesleywiser** [comment]
Hi all, MCP issues aren't meant for discussion, we have a separate [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/233931-xxx/topic/Update.20the.20existing.20musl.20targets.20to.20be.20dy.E2.80.A6.20compiler-team.23422) for that. Let's please move the discussion to that thread. Thanks!

**Comment by androm3da** [comment]
I'm happy to review or contribute changes necessary for hexagon to support this change.

**Comment by vi** [comment]
Will buildability of static musl be _tested_ automatically on CI even if/when dynamic musl becomes default?

Or will static flavour of musl become effectively Tier 3 instead of Tier 2?

**Comment by matthieu-m** [comment]
A Zulip thread/stream is very awkward to parse when it comes to searching for whether a question has already been asked, discussed, or answered.

I would recommend aggregating questions as well as their answers (if any) and the salient points of the discussion (if any) together in some sort of FAQ document... for example in the above MCP itself.

That is, I am fine with the discussion occurring on Zulip (or wherever) but I recommend that it be summarized in a more accessible manner (aggregated/summary) and at a more static location (nobody likes to scroll dozens of pages).

**Comment by nikomatsakis** [comment]
I think adding a FAQ to the template and collecting major points raised in the conversation is a good idea.

**Comment by Timmmm** [comment]
Uhm... from the thumbs ups here it kinda looks like everyone agreed this was a bad idea (or at least premature without a simple alternative)... and then it was accepted?

You guys should at least post the reasoning behind this decision.

**Comment by Timmmm** [comment]
I skimmed the Zulip thread and it seems like the conclusion was that initially Rust will look for a system copy of Musl and dynamically link with that, if available, and fall back to static linking. And maybe there will be some kind of `--static` flag. That seems reasonable.

**Comment by jman-schief** [comment]
@Timmmm a bit more context. Approving and closing the MCP is meant to acknowledge the issue and that actions will be taken ("ok, we gotta do something about it").
As you point out, the general idea is to lay out a clear migration path (deprecation notes, warnings, etc.) where we will fix the default musl target behaviour by providing as much information as possible so to hopefully not disrupt users' workflows (CIs and such).

**Comment by apiraino** [comment]
@Timmmm a bit more context. Approving and closing the MCP is meant to acknowledge the issue and that actions will be taken ("ok, we gotta do something about it").
As you point out, the general idea is to lay out a clear migration path (deprecation notes, warnings, etc.) where we will fix the default musl target behaviour by providing as much information as possible so to hopefully not disrupt users' workflows (CIs and such).

**Comment by WhyNotHugo** [comment]
As far as I can see from history here an don Zulip, the consensus is that this should move forward, but there's not (yet) a tracking issue for this.

Is it okay if I create a tracking issue for this in https://github.com/rust-lang/rust (e.g.: using the `Tracking Issue` template)?

**Comment by RalfJung** [comment]
Yes opening an issue would make sense.

Also the justification could link to [this thread](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/bootstrapping.20on.20s390x.2Fmips.20for.20musl/near/228065374) -- Rust's current mode of use of musl is a consequence of lack of coordination with the musl maintainers (who would have told us from the start that we shouldn't make static linking the default, but sadly they were not consulted when musl was added to rustc).

**Comment by NobodyXu** [comment]
I am the maintainer of `cargo-binstall` which is a drop-in replacement for `cargo-install` using pre-built artifacts and I'd like to pledge to not change this.

Part of the reason why anybody uses it is to create a statically linked binary, and changing it to dynamic linking will break many CIs and expectations.

`cargo-binstall` currently fallbacks to musl targets in case glibc isn't available or if there's no pre-built for gnu targets.

Changing musl to dynamic linking would make fallback to musl useless and would break expectations of our users.

**Comment by ssokolow** [comment]
Without a change like this, the musl target is just flat-out incompatible with various use-cases involving platforms that use musl-libc as the system libc.

The intent is to make static musl-libc use enabled via something like the `-C target-feature=+crt-static` that you already need for static linking on Windows so, in that sense, it's also a push for greater consistency across targets.

**Comment by NobodyXu** [comment]
It indeeds make it more compatible, but it also break existing scripts/CIs and we can no longer just fallback to musl target, expecting a statically linked binary.

**Comment by RalfJung** [comment]
> It indeeds make it more compatible, but it also break existing scripts/CIs and we can no longer just fallback to musl target, expecting a statically linked binary.

The fact that our musl targets work like that is a consequence of us screwing up and not coordinating with the musl maintainers. It's convenient for some cases but bad for others.

Everyone who wants static linking should start adding ` -C target-feature=+crt-static` to their flags now, to make this transition as smooth as possible. Of course we'll have a transition phase and everything, but keeping the current default is IMO not an option.

**Comment by vi** [comment]
Maybe there should be some easier way to turn on `+crt-static` which does not involve config files or `RUSTFLAGS`? E.g. special target name `x86_64-unknown-linux-musl-static`, which resolves to `x86_64-unknown-linux-musl` + `target-feature=+crt-static`.

**Comment by bjorn3** [comment]
There is no ABI incompatibility between the static and dynamic version, so I don't think a separate target makes sense. Also if you are on a musl distro and want to produce statically linked executables you now need two targets installed. The dynamically linked one for rustc as otherwise it can't load proc macros, and the statically linked one for the executable to build. I think having a profile option for crt-static separate from rustflags makes more sense. You can set those per-target too as well using an env var. In addition cargo can decide to ignore it when necessary and avoid recompilation of everything when switching between the two options. Amd if you really want maybe `cargo build` could have an extra cli flag for this.

**Comment by NobodyXu** [comment]
I think having something like `$cpu_arch-alpine-linux-musl` makes sense for me, since AFAIK Alpine is the only distro that uses musl libc by default and have the dynamic library installed.

For all other `$cpu_arch-unknown-linux-musl`, they likely don't have musl libc installed and it still makes sense to link with musl libc statically most of the time.

**Comment by kpcyrd** [comment]
There are multiple Linux distributions that use dynamic linking and musl libc, most notably:

1. Alpine Linux
2. Void Linux
3. OpenWRT

**Comment by NobodyXu** [comment]
Thanks, I didn't know that.

**Comment by ernsteiswuerfel** [comment]
> There are multiple Linux distributions that use dynamic linking and musl libc, most notably:
> 
>     1. Alpine Linux
> 
>     2. Void Linux
> 
>     3. OpenWRT

4. Gentoo Linux

**Comment by vi** [comment]
> I don't think a separate target makes sense ...

I didn't mean a separate target, I meant a way to alias existing target + a compiler option. `x86_64-unknown-linux-musl-static` is supposed to turn into `x86_64-unknown-linux-musl` early in tools like Cargo or Rustup.

**Comment by est31** [comment]
@NobodyXu if you want to read more, please read:

* the PR where people pointed out that statically linking musl is actually a policy violation on a bunch of musl distros: https://github.com/rust-lang/rust/pull/82556 . the compiler team decided to just change the default instead of adding specific dynamically linked targets.

* the hackmd from the compiler meeting where multiple approaches were studied: https://hackmd.io/YoAGSxUsRWumVvbRiHddrg

* for historic curiosity, the original PR that added musl to rust: https://github.com/rust-lang/rust/pull/24777 . it also has a link to a [reddit thread](https://old.reddit.com/r/rust/comments/33boew/weekend_experiment_link_rust_programs_against/) out of which the PR was born out of, which explored musl for the purposes of having a libc that one can link against statically. this explains why musl was originally statically linked. Ideally it should have been dynamically linked from the start, but these links show that people added musl as a means to get a statically linked libc. only later it was realized that both the musl maintainer and the musl distro .

also, maybe too late at this point, but the place to discuss an MCP is in the [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/233931-xxx/topic/Update.20the.20existing.20musl.20targets.20to.20be.20dy.E2.80.A6.20compiler-team.23422) associated to it, not the github thread of the MCP.

**Comment by RalfJung** [comment]
> only later it was realized that both the musl maintainer and the musl distros prefer dynamic linking.

That's really the main point for me. We should respect the policy and decisions of the people maintaining the target we're building for.

Having `cargo build --static` as an alias-of-sorts for `RUSTFLAGS="-C target-feature=+crt-static" cargo build` makes a lot of sense; cargo knows a bunch of rustc flags (such as optimizations and debug assertions), it can also know about this one. That would be a `cargo` feature request.

**Comment by est31** [comment]
> Having `cargo build --static` as an alias-of-sorts for `RUSTFLAGS="-C target-feature=+crt-static" cargo build` makes a lot of sense;

imo that would go further than just statically linking libc. I'd expect it to also statically link all the native libraries the project depends on through either build.rs or other means. cargo could set some env var or such that projects then should respect. that's usually what people want when they want static linking, they want everything to be linked statically, not just libc.

**Comment by bjorn3** [comment]
I believe there is a cfg exported for users to determine if crt-static is used. On most targets crt-static mandates full static linking, though not all targets. There is a target spec key for this.

**Comment by est31** [comment]
Hmm yeah one can do `#[cfg(target_feature = "crt-static")]` and build.rs scripts can check `CARGO_CFG_TARGET_FEATURE` as per [this](https://rust-lang.github.io/rfcs/1721-crt-static.html) RFC. Ultimately, this is best discussed in the appropriate issue in the cargo repo.

**Comment by NobodyXu** [comment]
Thanks @est31 will have a read of them

**Comment by xbjfk** [comment]
Hi,
I know it's been quite a while since the last comment on this, but I thought I would add my two cents.
Overall, I support this change.
I accept that it will break existing CI scripts, however the current situation is even worse.
Currently, the (arguably) three largest distros shipping musl all patch rust to disable default static on musl ([Gentoo](https://github.com/gentoo/gentoo/blob/master/dev-lang/rust/files/1.75.0-musl-dynamic-linking.patch), [Alpine](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/rust/musl-fix-linux_musl_base.patch) and [Void](https://github.com/void-linux/void-packages/blob/master/srcpkgs/rust/patches/0002-Remove-nostdlib-and-musl_root-from-musl-targets.patch)) - meaning currently the musl target changes *depending on what distro it's run* - which is especially concerning, given Alpine's popularity as a distro for containers. Someone in a linked issue already got caught out by this.
Another problem is that a lot of packages make assumptions that musl libc means static linking - an example of this is [llvm-sys](https://gitlab.com/taricorp/llvm-sys.rs/-/blob/main/build.rs#L651), leading to distro users or maintainers having to patch this behavior out for each package that assumes it (although this behaviour is incorrect anyway even currently).
There really doesn't seem to be a way forward without annoying a large group of people, and I think it's best to rip the band aid off now and remove the necessity for downstreams to diverge as much rather than wait as more and more infrastructure depends on this implicit behavior.

**Comment by kpcyrd** [comment]
Could this be done as part of the upcoming 2024 edition?

**Comment by FeldrinH** [comment]
If I understand correctly, the current plan is that eventually the existing musl targets will all be dynamically linked by default. Is there a tracking issue for this change?
