### ISSUE TITLE
Teach `rustc` to use OSC8 on nightly / Embedded links in terminal output

### ISSUE THREAD

**Issue by estebank** [rust-lang/compiler-team#587]
# Proposal

Add a nightly flag `-Zterminal-urls=y|on|yes|n|off|no|auto` that configures enabling embedded links in terminal output. Start using this configuration only in nightly, defaulted to `off`. The specifics of `auto` will be determined through experimentation.

This will allow us to customize the printed output with hyperlinks to relevant documentation, or to local files (by using `file://`, but leveraging that can be fraught for people using ssh).

An example of what this would look like in practice can be seen in this video:

https://user-images.githubusercontent.com/1606434/217785174-51ab0669-af81-48ea-960a-1b674b92c3cc.mov

https://github.com/rust-lang/rust/pull/107838 shows what the code changes required would be.

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention then
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by epage** [comment]
Is there a tracking issue for discussing this?

Cargo is stabilizing link support in 1.75 (see rust-lang/cargo#12889)
- We offer [`term.hyperlinks`](https://doc.rust-lang.org/nightly/cargo/reference/config.html#termhyperlinks) to control it
- We are auto-detecting with [supports-hyperlinks](https://crates.io/crates/supports-hyperlinks)
  - Unsure how we feel about the `FORCE_HYPERLINK` env variable; we aren't documenting it
  - We do have an extra check beyond that because a file path link wasn't correctly working on iTerm2
  - To drop `is-terminal` dep, I'm tempted to just copy/paste the code

It'd be good for cargo and rustc to coordinate on when links are shown (so one doesn't auto-detect when the other doesn't) and other behavior.

**Comment by estebank** [comment]
1) we should absolutely unify the behavior across rustc and cargo.
2) Be aware that "just" checking if the terminal supports hyperlinks is insufficient: if using a terminal sshing into a remote development machine, the links will either use the full ssh format (`username@host:/path/to/file`) or to a "fake" local path (`/path/to/file/that/doesn't/exist/locally`), breaking the currently working auto-linking that the VSCode terminal has. Are you certain that this is already correctly handled on the cargo side?

**Comment by epage** [comment]
For `file:` links, we include the hostname according to [this gist](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#file-uris-and-the-hostname)
