### ISSUE TITLE
Support response files generated by ninja with `@ninja:path` syntax

### ISSUE THREAD

**Issue by djkoloski** [rust-lang/compiler-team#684]
# Background

A response file (also called an argument file) is a special command-line argument that instructs a program to read additional arguments from a file. Response files are prefixed with `@`, and so invocations usually take the form `rustc @args.txt`. Response files exist to work around maximum line length limitations on various operating systems.

# Motivation

This proposal is intended to provide a solution for [this issue](https://github.com/rust-lang/rust/issues/116068) and allow rustc to integrate with ninja more easily. It also sets a convention for supporting response files with different formats in rustc.

Today in rustc, response files are parsed as newline-delimited files where each argument exists on a single line. Any spaces on a line are treated as part of that argument, and surrounding quotes are passed through verbatim. This makes it difficult to integrate rustc with ninja, which generates response files with space-delimited (possibly-)quoted arguments. This functionality is built into ninja itself with the `rspfile` option. Rustc's response file format is incompatible with ninja's generated format, and the maintainer of ninja is unlikely to make a special case for us.

# Proposal

We propose changing the behavior of rustc and cargo to accept response file arguments of the form`@ninja:path`. Those arguments are treated as response files generated by ninja which follow its conventions for argument delimitation, quoting, and escaping.

# Mentors or Reviewers

@tmandry is on the Fuchsia team and holds some stake in this MCP.

@Nilstrieb has expressed interest in reviewing an MCP for this behavior change.

@jsgf added response file handling to rustc in [#63175](https://github.com/rust-lang/rust/pull/63175) roughly four years ago. Argument quoting and character escaping [was discussed](https://github.com/rust-lang/rust/pull/63175#issuecomment-517055461) but not implemented.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by djkoloski** [comment]
cc @fangism originally raised this in #116068.
cc @p1n3appl3 who provided an implementation in #116954.

**Comment by jsgf** [comment]
Yeah I ultimately decided on the "one line per arg" was a better fit for complexity vs capability. 

I have a few of questions about this proposal:

Firstly, what's the motivation? The closest this comes is "brings rustc's response file parsing more in line with existing tooling" but doesn't say specifically why this is desirable. Is it because you want to interoperate with something that will only emit args files in this format? Or you want to share the same file between multiple different commands?

Secondly, what's the backwards-compatibility story? If you just change the syntax of the files that `@` consumes, it's a clear break. What about existing use-cases? Are you going to simply break them? Or will you support both syntaxes? Distinguished how? For a while? Forever? 

Also, independent of all that:
> - Text within single quotes (') and double quotes (") are treated as a single argument (the surrounding quotes are stripped)
> - Backslashes are treated as escape characters which preserve the literal value of the next character except within single-quoted arguments

Ugh, I really dislike that Bourne-shell `'` vs `"` magic - it's basically spurious extra complexity without any real benefit.

I felt when researching existing argsfile formats there was a lot of unjustified complexity and a lot of people copying other examples without a particularly strong rationale. In other words, choosing this much simpler "one arg per line" format was an explicit break with tradition to avoid all the quoting mess.

**Comment by tmandry** [comment]
This MCP has had several revisions in response to feedback, and at this point only bikeshed details are left.

@rust-lang/compiler would someone please kick off an FCP?

**Comment by tmandry** [comment]
Actually, after some discussion with the compiler team it sounds like the right process is to start with an unstable-gated flag, in which case this does **not** need a full team sign-off and a second is all that is necessary.

@rustbot second
